export const homeData = [
  {
    id: 1,
    name: "KGF chapter 2",
    rating: 4.9,
    time: "2hr : 45 mins",
    desc: "KGF Chapter 2 is an action-packed Kannada blockbuster starring Yash as Rocky, who rises to power in the Kolar Gold Fields while facing deadly enemies.",
    starring: "Rocking star YASH,sanjay dutt",
    genres: "Action",
    tags: "Action,Mother sentiment",
    cover: "../images/home1.jpg",
    video: "../video/",
    date: "20-Jan-2022",
  },
  {
    id: 2,
    name: "Mr & Mrs Ramachari",
    rating: 4.6,
    time: "3hr",
    desc: " romantic drama starring Yash and Radhika Pandit. The film beautifully portrays the passionate love story of a rebellious young man, Ramachari, and his determined lover, Divya, blending intense romance with emotional drama.",
    starring: "Yash ,Radhika Pandith",
    genres: "Love,Friendship",
    tags: "friendship,Action,Family",
    cover: "../images/home2.jpg",
    video: "../video/",
    date: "10-JUL-2017",
  },
  {
    id: 3,
    name: "Googly",
    rating: 4.8,
    time: "2hr : 58mins",
    desc: " is a popular Kannada romantic comedy starring Yash and Kriti Kharbanda. Directed by Pavan Wadeyar, the film follows the love story of Sharath and Swathi, filled with misunderstandings, humor, and heartfelt emotions. Its catchy music and Yash's charming performance made it a major hit. ",
    starring: "Yash,Kirti Kharbanda",
    genres: "Love",
    tags: "Love,Action ",
    cover: "../images/home3.jpg",
    video: "../video/",
    date: "20-FEB-2015",
  },
  {
    id: 4,
    name: "Devil",
    rating: 4.9,
    time: "2hr : 48mins",
    desc: "Devil The Hero is an upcoming Kannada action film directed by Prakash Veer, featuring Darshan Thoogudeepa in the lead role. The movie promises a gripping saga of power, vengeance, and true love, with high-octane action sequences and intense drama",
    starring: "D Boss Darshan Thoogudeepa",
    genres: "Action",
    tags: "Action , mass ",
    cover: "../images/home4.jpg",
    video: "../video/",
    date: "12-oct-2025",
  },
]
export const upcome = [
  {
    id: 1,
    cover: "../images/upcome/u1.jpg",
    name: "Manikya",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u2.jpg",
    name: "power",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "Rajakumar",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u4.jpg",
    name: "Gandadagudi",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u5.jpg",
    name: "Jumbo Queen",
    time: "2hr : 38mins",
  },
]
export const latest = [
  {
    id: 1,
    cover: "../images/upcome/u6.png",
    name: "King of Jungle",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u7.jpg",
    name: "Hebbuli",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u1.jpg",
    name: "Manikya",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u5.jpg",
    name: "Jumbo queen",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u4.jpg",
    name: "Gandadagudi",
    time: "2hr : 38mins",
  },
]

export const trending = [
  {
    id: 1,
    name: "Rajakumar",
    rating: 4.7,
    time: "2hr : 46mins",
    desc: "Drama is a popular Kannada romantic comedy-drama directed by Yogaraj Bhat, starring Yash and Radhika Pandit.",
    starring: "PuneethRajakumar",
    genres: "Father sentiment",
    tags: "Action, Emotion,country first",
    cover: "../images/img/slide1.jpg",
    date: "20-Jan-2022",
  },
  {
    id: 2,
    name: "Masterpiece",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "Masterpiece is an action-packed Kannada film starring Yash as Yuva, a rebellious young man with a complex personality who fights against corruption and injustice.  ",
    starring: "Yash,chikanna",
    genres: "Action",
    tags: "Action,mass,Family",
    cover: "../images/img/slide2.jpg",
    date: "10-JUL-2017",
  },
  {
    id: 3,
    name: "Gaja kesari",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "Gajakesari is a Kannada action-drama film starring Yash, directed by Krishna. The movie tells the story of Krishna, a young man who discovers his past life connection with a warrior and an elephant",
    starring: "Yash ",
    genres: "Action",
    tags: "Action , friendship",
    cover: "../images/img/slide3.jpg",
    date: "20-FEB-2014",
  },
]
export const recommended = [
  {
    id: 4,
    cover: "../images/rec/rec1.jpg",
    name: "AnjaniPutra",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/rec/rec2.jpg",
    name: "Ranavikram",
    time: "2hr : 38mins",
  },
  {
    id: 1,
    cover: "../images/rec/rec3.jpg",
    name: "Yuvaratna",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/rec/rec4.jpg",
    name: "Power",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "Rajakumar",
    time: "2hr : 38mins",
  },
]
